- sysctl: name=net.ipv4.ip_forward value=1 state=present reload=yes sysctl_set=yes
- service: name=docker state=started enabled=yes
- service: name=ntp state=started enabled=yes
- service: name=kubelet state=started enabled=yes
- sysctl: name=net.bridge.bridge-nf-call-ip6tables value=1 state=present reload=yes sysctl_set=yes
- sysctl: name=net.bridge.bridge-nf-call-iptables value=1 state=present reload=yes sysctl_set=yes
