- shell: "mkdir -m 755 -p /etc/apt/keyrings && apt-get update -y && apt-get install -y apt-transport-https ca-certificates curl gpg -y && curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg"
- apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /'
    state: present
- name: install docker and kubernetes
  apt: name={{ item }} state=present allow_unauthenticated=yes
  with_items:
    - docker.io
    - kubelet
    - kubeadm
    - kubectl
    - ntp
