---
- name: prepare all
  hosts: all
  become: True
  gather_facts: True
  roles:
    - { role: 'prepare', tags: 'prepare' }

- name: init master
  hosts: masters
  become: True
  gather_facts: False
  roles:
    - { role: 'master', tags: 'master' }
